### ISSUE TITLE
add --render parameter

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/tape-run#21]
because if you do

```bash
$ browserify test.js | tape-run | tap-spec
```

you won't get the correct exit code. Better:

```bash
$ browserify test.js | tape-run --render="tap-spec"
```

**Comment by ericmorand** [comment]
How would you use that inside an npm script?

```
"scripts": {
    "test": "browserify test.js | tape-run --render='tap-spec'"
}
```

Fails miserably.

**Comment by juliangruber** [comment]
That works for me, please post your exact error in a new issue

**Comment by ericmorand** [comment]
That's OK, sorry about that. I forgot to install `tap-spec`. (:ashamed:)
