### ISSUE TITLE
istanbul coverage

### ISSUE THREAD

**Issue by rtsao** [juliangruber/tape-run#31]
It would be nice to be able to extract test coverage information.

The way I've started to implement this (in https://github.com/rtsao/tape-run/tree/coverage and  https://github.com/rtsao/browser-run/tree/messages) is as follows:

1) Add a generic duplex stream between `browser-run` and the browser using https://github.com/substack/shoe

2) In `tape-run`, prepend input test source with a script that listens for a message from the duplex stream, then sends the coverage information back.

3) If test completes with no errors, send a message to the browser via the duplex stream to signal tests have completed. When coverage is returned, exit. Or if the test returned errors, just exit.

Do you have any thoughts on this? I'm happy to create a PR when I'm finished. Any interest in including this sort of functionality? It would be nice to not use a fork.

**Comment by juliangruber** [comment]
it might not be easy to do with istanbul, but it is using coverify:

```bash
$ browserify -t coverify script.js | tape-run | coverify
TAP version 13
# one
ok 1 true

1..1
# tests 1
# pass  1

# ok

# coverage: 10/10 (100.00 %)
```

**Comment by juliangruber** [comment]
feel free to reopen if you have further concerns

**Comment by bendrucker** [comment]
For anyone using Istanbul I made [tape-istanbul](https://github.com/bendrucker/tape-istanbul). The example references tape-run but it'll work for anything where you pipe in code and get back console logs as stdout. substack's method in coverify for wrapping code in coverage functions and then extracting coverage data streamingly is a lot more clever. The only reason I made an Istanbul utility is that coverify's deps are a bit out of date and it has some trouble with ES6 transpilation / source maps. Istanbul handles that better at the moment.

**Comment by juliangruber** [comment]
fyi the above would work with node as well:

```bash
$ browserify -t coverify script.js | node | coverify
```

good to know about tape-istanbul though!

**Comment by flekschas** [comment]
When I run `rollup -c ./rollup.test.config.js | tape-run | coverify` the output of `coverify` is always empty even though `tape-run` prints test results. Did something general change? I noticed that `tape-istanbul` also doesn't output anything.

**Comment by juliangruber** [comment]
Did you include the coverify plugin in your rollup setup?

**Comment by flekschas** [comment]
Oh nevermind, I guess it's not actually possible to use coverify in combination with rollup. My bad! :)
