### ISSUE TITLE
Add example to use tape-run on any Linux environment

### ISSUE THREAD

**Issue by fraserxu** [juliangruber/tape-run#32]
Hi @juliangruber I'm trying to use tape-run as a light-weight testing running environment for my [react-testing-recipes](https://github.com/fraserxu/react-testing-recipes#to-run-your-test-in-the-browser-with-tape-run) repo here. 

One thing I've noticed is that the setup only works on Mac but not Linux, I saw you have a section to demo how to use it with [travis](https://github.com/juliangruber/tape-run#travis), but unfortunately I can not use Travis in our project, it's a customised linux testing server.

I did a few research and end up with this setup in a docker environment [docker-tape-run](https://github.com/fraserxu/docker-tape-run)

The idea it's pretty simple by installing xvfb manually and start a sever on the system(but could also be troublesome as there's no error message at all when running on Linux), I thought this could be something helpful to be add to the readme here?

Please let me know what you think and I'll send a pull request if you are OK with that, thanks for the project by the way!

**Comment by juliangruber** [comment]
It _should_ work out of the box when your linux installation has some kind of graphical environment running. I'll add a link to your machine and some generic linux instructions to the readme.
