### ISSUE TITLE
Missing stack trace

### ISSUE THREAD

**Issue by unional** [juliangruber/tape-run#36]
Running with:
- tape-run@2.1.3
- blue-tap@0.2.0 -> tape@4.5.1

Output:
```sh
  ---
    operator: equal
    expected: false
    actual:   true
    at: Test.assert [as _assert] (jspm_packages/npm/tape@4.5.1/lib/test.js:215:9)
  ...
```
It should be pointing to the test:
```
    t.test('should define the method if it is not already defined', (test) => {
        let defaultCalled = false;
        let subject: any = {};
        defineDefault(subject, 'notExist', function() {
            defaultCalled = true;
        });
        subject.notExist();
        test.isEqual(defaultCalled, false); // <-- here
        test.end();
    });
```
Don't know if it is related to https://github.com/systemjs/builder/issues/547 or an issue with `tape`

**Comment by juliangruber** [comment]
can you post a snippet that i can run, to try this out?

**Comment by juliangruber** [comment]
closing for lack of interest

**Comment by unional** [comment]
@juliangruber sorry for not getting back to this. Somehow it fall through the cracks. It is still happening and I think it is due to `tape` itself rather than `tape-run`. The same occurs as I run it through `karma`. 🌷
