### ISSUE TITLE
Does the wait option really work?

### ISSUE THREAD

**Issue by binarykitchen** [juliangruber/tape-run#38]
Running some longer tests here interacting with DOM stuff and would like to add a timeout. But looks like it does not work

`browserify test/**/*.test.js | tape-run --wait=10`

Tests usually take 2 seconds but with the above, they don't timeout.

**Comment by juliangruber** [comment]
can you give me a script to reproduce? i haven't had this problem yet

**Comment by binarykitchen** [comment]
false alarm, works for me now. had a wrong setup. sorry
