### ISSUE TITLE
console.log in code does not appear in tape output

### ISSUE THREAD

**Issue by binarykitchen** [juliangruber/tape-run#39]
When I add a `console.log('something')` in the code I am testing with tape-run, that output is not shown. Any ideas why?

**Comment by juliangruber** [comment]
it works for me, can you give me a gist to reproduce?

**Comment by refactorized** [comment]
Are you piping to faucet or another tap processor?  Faucet will swallow console logs for instance.

**Comment by juliangruber** [comment]
Closing for no response
