### ISSUE TITLE
exit code is 1

### ISSUE THREAD

**Issue by vvo** [juliangruber/tape-run#43]
Using latest tape-run, simple test, node v5.11.0, have you seen anything like that?

**Comment by vvo** [comment]
seems to be an electron issue, maybe an uncaught exception occured in the browser, even if all tests passed, weird!

**Comment by vvo** [comment]
still getting the error, here: https://github.com/substack/insert-css/pull/2

**Comment by vvo** [comment]
As soon as I do any DOM manipulation, seems to get the error. simple t.ok(true) works

**Comment by juliangruber** [comment]
can you give me a gist that reproduces the problem?

**Comment by vvo** [comment]
Oh my bad, I had a console.log('ok') somewhere in my code, thus triggering a bad parsing of the tape output. I am so dumb. Thanks

**Comment by juliangruber** [comment]
things like that happen, don't worry :)
