### ISSUE TITLE
More explicit wording in Travis config documentation

### ISSUE THREAD

**Issue by barneycarroll** [juliangruber/tape-run#45]
Hiya, I read the README and [the part about how to get Electron working in Travis](https://github.com/juliangruber/tape-run#headless-testing), but didn't grok that AFAICT this is imperative for getting tape-run to work with Travis at all. At the moment it reads more like an aside for technically-minded people who may have their own esoteric reasons for preferring Electron to Phantom, and it still wasn't obvious to me that this advice was necessary (in the absence of more involved concerns) to get Travis to build after repeated failures there, since [Travis doesn't log any informative error messaging in the case of failing to do this](https://travis-ci.org/barneycarroll/muty/jobs/153551302#L506), and [its own document suggests that Phantom is a panacea](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS).

I would PR, but I'm not confident about the exact nature of the conflict in assumptions to write up *why* this is the case :sweat_smile:

**Comment by juliangruber** [comment]
thank you for reporting this issue, and explaining so well :)

how is this? https://github.com/juliangruber/tape-run/blob/master/README.md

**Comment by barneycarroll** [comment]
WFM! +1
