### ISSUE TITLE
No error output when running tests through tape-run

### ISSUE THREAD

**Issue by binarykitchen** [juliangruber/tape-run#48]
Unit tests of my npm library https://github.com/binarykitchen/videomail-client fail on travis ci each time (https://travis-ci.org/binarykitchen/videomail-client) and there's not much information why.

Also have asked a dev from travis to reproduce this on a docker image. Here the Gist log
https://gist.github.com/BanzaiMan/0450b14967f6677a68f253781586a058

Doesn't say much either. Is tape-run somehow hiding the real error? Command to run test `browserify test/**/*.test.js --debug | tape-run --render=tap-spec`

Hope anyone has a clue?

**Comment by juliangruber** [comment]
does this happen without the tap-spec reporter too?

**Comment by binarykitchen** [comment]
hmmm, behaviour is same with or without tap-spec.

and funnily, since i switched to nodejs v7.2.1 here, i can reproduce this on my machine too, not just on travis

failing videomail-client test output:
https://gist.github.com/binarykitchen/2ec3308335e94dbd6f6494b3cc5dac60

and its npm-debug.log
https://gist.github.com/binarykitchen/c502561b8ea72fe8b05e404a3c003744

why does it abort in the middle and doesn't say much?

**Comment by binarykitchen** [comment]
ah, there are some bugs in my code :)

weird they didn't show up under node v6.3.1 earlier

**Comment by juliangruber** [comment]
maybe there's still something we can do here in order not to swallow those. can you show me what exactly caused it?

**Comment by binarykitchen** [comment]
I think it was an undefined variable that tore down the whole unit test process:

```
        err = browser.checkRecordingCapabilities()
        console.log(err)
        tt.equal(err.message, 'Sorry, your browser has no webcam support')
        tt.ok(err.explanation.indexOf('your browser must support') >= 0)
```

err was `undefined` due to a bug inside my code I just fixed.

But my point is, tape-run shouldn't crash and be somewhat safe and at least print an error.

Maybe a try-catch block wrapping the test fn would solve this? cc @juliangruber

**Comment by binarykitchen** [comment]
@juliangruber happening again here - any news on this one?

**Comment by binarykitchen** [comment]
ummm, looks like the other lib, tape-catch, is the solution. i think this functionality should be in tape core.

**Comment by refactorized** [comment]
just use tape-catch in place of tape - working for me so far without any additional changes.

**Comment by juliangruber** [comment]
cool, closing here then :)

**Comment by jayeshbhoot** [comment]
@refactorized @binarykitchen @juliangruber A failing test still hangs the test run, even with `tape-catch`. How did you make `tape-run` work with `tape-catch`?
