### ISSUE TITLE
Can't install offline

### ISSUE THREAD

**Issue by yoshuawuyts** [juliangruber/tape-run#53]
https://github.com/juliangruber/tape-run/blob/master/package.json#L20 means `--cache-min Infinity` freezes. Any chance you could publish https://github.com/substack/tap-finished/pull/6 as `@juliangruber/tap-finished` and update it here? Would allow for better offline hacking timeee :sparkles: Thanks!

**Comment by juliangruber** [comment]
sure thing!

**Comment by yoshuawuyts** [comment]
Awesome, thanks! :D
