### ISSUE TITLE
Weird SyntaxError when using electron

### ISSUE THREAD

**Issue by binarykitchen** [juliangruber/tape-run#59]
```
~/c/videomail-client ❯❯❯ browserify test/**/*.test.js --debug | tape-run                             develop ✭ ✖ ✱
(node:24784) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
SyntaxError: Invalid or unexpected token
```

But does not happen when using `--browser chrome`. How can I investigate the cause best or it is a known Electron issue?

**Comment by juliangruber** [comment]
Hey, can you upload the file the browserify command outputs?

**Comment by juliangruber** [comment]
You can also send it to me via mail privately (julian@juliangruber.com) if that's an option

**Comment by binarykitchen** [comment]
@juliangruber easy to reproduce. just git clone https://github.com/binarykitchen/videomail-client and then run `npm i && npm run test` ... curious here what you will find

**Comment by juliangruber** [comment]
Oh, yeah, dang, will get a fix out this week!

**Comment by juliangruber** [comment]
The issue starts with this line: https://github.com/bfred-it/iphone-inline-video/blob/master/index.js#L9

Without the proper encoding it seems, browsers will not parse this. Should have a fix soon!

**Comment by juliangruber** [comment]
fixed in electron-stream, with a fresh installation of tape-run you should also get that. otherwise, clear your cache and try again :)

**Comment by binarykitchen** [comment]
yep indeed, it's fixed now. thanks dude

**Comment by marlun** [comment]
I'm getting this now with Node 7.9.0 and tape-run 3.0.0 and browserify 14.3.0. Running `browserify test.js | tape-run`.

**Comment by juliangruber** [comment]
@marlun can you link me to the source or a reproducable example?

**Comment by tunnckoCore** [comment]
I also have same issue. It appears when using `tape-run` and also `browser-run`. I'm not using `browserify`, but Rollup. And the bundle is perfectly valid javascript compiled to 0.10 that runs with raw `node test.js` without problems, code is StandardJS-ed and Prettier-ed.

**Comment by juliangruber** [comment]
@tunnckoCore can you show me the output for `node dist/bundled-test.js | tape-run --browser electron` too?

**Comment by tunnckoCore** [comment]
@juliangruber nothing. Should manually terminate it and shows me popup window that "main process is .. something", but not always, very strange.

I'll post when I get it again.

**Comment by tunnckoCore** [comment]
hm.. my fault, that was for something other :D 

```
(node:23857) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
ReferenceError: require is not defined
    at http://localhost:39945/:2:14

```

**Comment by juliangruber** [comment]
try `tape-run --node`, that enables `require()` support. otherwise it will need to be handled by your bundler

**Comment by tunnckoCore** [comment]
Huh. Yea that way works, didn't notice that flag.

But yea, in anyway it seems that it's not package for my case.

**Comment by juliangruber** [comment]
ok
