### ISSUE TITLE
window.location.search goes wild

### ISSUE THREAD

**Issue by timwis** [juliangruber/tape-run#62]
Hey, I think I've come upon some peculiar functionality...

```javascript
var test = require('tape')

test('search query', function (t) {
  window.location.search = 'foo=bar'
  t.ok(true)
  t.end()
})
```
And running with:
```bash
browserify test.js | tape-run
```
Somehow it's run 6 times in the console.

```tap
TAP version 13
# search query
ok 1 should be truthy

1..1
# tests 1
# pass  1

# ok

TAP version 13
# search query
ok 1 should be truthy

1..1
# tests 1
# pass  1

# ok
```
(I only pasted 2 for brevity)

Odd, right? If you comment out the line setting `search` it works as expected.

EDIT: Seems to occur when setting `window.location.pathname` too

**Comment by juliangruber** [comment]
Try setting the search param in chrome, and you'll find that the page reloads - that's exactly what's happening when doing so in tape-run, as it's running a real browser.

I would suggest if you test a library that reads `window.location`, to allow for specific parameters to be passed in as arguments as well.

Does that make sense?

**Comment by timwis** [comment]
That makes sense, but still not sure why it would run 6 times. I'm writing higher level tests for choo, so not sure I can break these down further but I'll take a look. Thanks for replying.

**Comment by juliangruber** [comment]
yeah why it's exactly `6` times also isn't clear to me, it should instead run forever

**Comment by juliangruber** [comment]
you can't overwrite window.location...I looked at the tests of page.js [here](https://github.com/visionmedia/page.js/blob/master/test/tests.js) and they don't navigate away from the current page. You _could_ use webdriver + electron (spectron) for this however!

**Comment by fregante** [comment]
Closing because it works as expected
