### ISSUE TITLE
support for other bundler webpack and rollup

### ISSUE THREAD

**Issue by syarul** [juliangruber/tape-run#64]
test ```cat dist/build.js | tape-run``` failed with webpack. The stream freeze once inside ```@juliangruber/tap-finished```.

ref issue #35

**Comment by syarul** [comment]
closing the issue, since tape-run does work with webpack just need to add
```javascript
{
  node: {
    fs: 'empty'
  }
},

**Comment by juliangruber** [comment]
https://github.com/juliangruber/tape-run/commit/e6ea66cebd093d8e2a6b817f488b73514bce7e12
