### ISSUE TITLE
`</script>` tags inside the JS input causing errors.

### ISSUE THREAD

**Issue by mintchaos** [juliangruber/tape-run#66]
So our testing bundle ends up having a few script tags that we write to the page. To test other bits that read from those script elements. Those are in our test code as strings. such as `'<script type="text/json" name="capabilities"></script>'`. 

This causes browsers to throw errors when run through tape-run because the bundle is shoved into a script tag and browsers (electron in particular) get mad about that. 

For right now I've worked around this by just rewriting the script tags after bundling. But that's pretty janky:

```
browerify-my-tests | sed -e "s/<\/script/&lt;\/script/" | tape-run
```

Now, this is old code that still used jquery, and this could be avoided by creating script elements with proper JS, but it'd also be great if our bundle didn't blow up if it contained `</script>`. 

So… I guess my question is, what do you think the best way to deal with this is? My first thought was to pass the bundle as a <script src="bundle.js"> instead of entirely in a script tag, but wanted ask if you agreed with that approach.

**Comment by juliangruber** [comment]
Sourcing them bundle from a file seems like a safe way to approach this, yeah!

Currently i'm not having this issue myself though so i can't justify working on it. However, to whom is interested, the main point of interest is this: https://github.com/juliangruber/electron-stream/blob/master/index.js#L82-L100.

All the other browsers should work already (right?)
