### ISSUE TITLE
How to resize the browser window

### ISSUE THREAD

**Issue by axelpale** [juliangruber/tape-run#67]
I am developing a zoomable user interface library. Its headless tape-run test suite needs an **ability to set window size** to test how the lib behaves with windows of different sizes. However, tape-run does not provide options to specify the size. So how to overcome this?

The default windows size for `phantomjs` seems to be 400, 300 and for `electron` it is 800, 578. There is a JS method [window.resizeTo](https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo) but browsers do not and **should not allow** to call the method on the main window.

For electron, there is `require('electron').remote.getCurrentWindow().setSize(width, height)` that should change the size of the current window (see [remote](https://electronjs.org/docs/api/remote) and [BrowserWindow](https://electronjs.org/docs/api/browser-window)). The ability to call that from the test suite would be wonderful. Unfortunately `require('electron')` throws `TypeError: fs.existsSync is not a function`. The error is understandable, there is no `fs` module in the browser, although I have mocked it with `{}` as instructed by [webpack-tape-run](https://github.com/syarul/webpack-tape-run).

So how to solve this? How to resize the headless browser window created by **tape-run**?

**Comment by juliangruber** [comment]
try running adding the `--node` flag to tape-run, that should give you access to the `electron` module. hopefully that works!

**Comment by axelpale** [comment]
@juliangruber Thanks for the tip! I got it working with the following configuration:

**webpack.test.js:**

```
var webpackTapeRun = require('webpack-tape-run')
var path = require('path')

module.exports = {
  entry: {
    'smoke': './smoke.test.js',
  },
  context: path.join(__dirname, 'test'),

  node: {
    fs: 'empty',  // mock fs
  },

  output: {
    filename: '[name].test.js',
    path: path.join(__dirname, 'dist'),
  },

  plugins: [
    new webpackTapeRun({
      tapeRun: {
        browser: 'electron',
        node: true,  // allows window.require
        keepOpen: false,
      },
      reporter: 'tap-spec',
    }),
  ],

  stats: 'errors-only',
}
```

**smoke.test.js:**

```
var test = require('tape')
var unit = require('../index')
var electron = window.require('electron')

electron.remote.getCurrentWindow().setSize(1024, 768)

setTimeout(function () {
  console.log(window.innerWidth)  // outputs 1024
}, 100)
console.log(window.innerWidth)  // outputs 800

test('first test case', function (t) {
  ...
```

The beef seems to be
- enable `window.require` by setting `node: true`. The `window.require` will be resolved by the browser, not by webpack.
- mock `fs` to avoid webpack throwing error about missing `fs` at `require('tape')`
- import electron by `window.require('electron')`
- set the window size via electron remote and wait for it to take effect. Timeout of 10 ms was too quick in my case, 20 ms seems to do the job but I would not count on it. Maybe set 100 ms to play it safe.

I also found that simple `window.resizeTo` works but also after a similar delay. Previously I thought that the method was just deprecated but I had not accounted for the delay.

**Comment by axelpale** [comment]
Additional note: resize takes a bit longer within tests, 100 ms was too quick. To protect arbitrary delays breaking the test suite, one can listen for 'resize' event:

```
test('window resize test', function (t) {
  var W = 1024, H = 768

  t.equal(window.innerWidth, 800, 'default width 800')
  t.equal(window.outerHeight, 600, 'default height 600')

  window.resizeTo(W, H)
  window.addEventListener('resize', function () {
    t.equal(window.innerWidth, W, 'width match')
    t.equal(window.outerHeight, H, 'height match')  // note outer
    t.end()
  }, { once: true })
})
```
