### ISSUE TITLE
How to reset browser window state between tests?

### ISSUE THREAD

**Issue by axelpale** [juliangruber/tape-run#68]
Currently, a change in DOM at test 1 is still remains at test 2. In other words, **the state of the browser is shared** between test cases, which is something people try to avoid in unit tests. Is there **a best practice to reset browser state** between cases when using tape-run?

An obvious approach is to implement a setUp and tearDown routines into the test suite that **try** to undo all the changes. This however feels cumbersome, especially because some state changes are asynchronous, adding extra closure to each test case. In my case the async change is resizing of the browser window, that [requires async wait](https://github.com/juliangruber/tape-run/issues/67) to take place.

I was hoping to see an option where tape-run would run each test case in a separate browser window.

**Comment by juliangruber** [comment]
This is just as with node, all tests run in the same process so you need to prevent state collisions yourself.

We could implement something like this, however it requires that every single test case needs to be placed in its own file.

I think what would suit your demands better were if `test('name', fn)` would itself launch a new browser instance. Currently the way this module works is all tests are compiled into a single bundle and then shipped to a browser. But what you're looking for would instead be each test compiling its own bundle and launching a browser with it.

**Comment by axelpale** [comment]
Thanks for the clarification. Now I see that each case should have its own browser instance. For now, I curried the `test('name', fn)` to reset DOM and some other browser state variables. I think the approach is good enough for now. As you implied, browser instance per test would require a whole different approach.
