### ISSUE TITLE
Errors on Travis

### ISSUE THREAD

**Issue by TehShrike** [juliangruber/tape-run#71]
Long shot here, but has anyone else had issues running tests with tape-run on Travis recently?

My newest project has been testing fine locally with tape-run, but [failing on Travis because of tape-run](https://travis-ci.org/TehShrike/idle-until-urgent/branches).

You can see my experiments in the [recent commits on this branch](https://github.com/TehShrike/idle-until-urgent/commits/poking-at-travis).

**Comment by juliangruber** [comment]
the readme is your friend :) https://github.com/juliangruber/tape-run#headless-testing--travis

**Comment by TehShrike** [comment]
Oh man, I've used tape-run a dozen times on Travis before, how did I forget xvfb this time 😭 I wonder if Travis used to display a better error message or something

Thanks for your patience, I apologize for the annoyance!
