### ISSUE TITLE
Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by fergiemcdowall** [juliangruber/tape-run#74]
`tape-run` fails silently on my Ubuntu 18.04 machine. However it works perfectly on other environments that I have tried.

I have tried fiddling around with the recipe described under "For gnu/linux installations without a graphical environment", but to no avail.

Any tips or magic incantations that might help?

**Comment by juliangruber** [comment]
Hmm and there's no error message whatsoever? I'm sorry, that's bad experience. I don't have an Ubuntu machine at hand right now. Would it be possible for you to test on a _fresh_ Ubuntu 18.04 setup? Maybe something in your system configuration influences this.

Or is there someone else how can try to reproduce on their machine?

**Comment by fergiemcdowall** [comment]
FWIW `browser-run` works fine on my Ubuntu 18.04

```
fergus 💥  ➜ echo "console.log('Hey from ' + location); window.close()" | browser-run
Hey from http://localhost:38799/
```

**Comment by fergiemcdowall** [comment]
@juliangruber indeed! I really like `tape-run`, so I will continue to poke and prod it to try to get it to work on my setup.

**Comment by fergiemcdowall** [comment]
Actually the very latest version `6.0.0` works perfectly on Ubuntu. I should of course have checked this before opening an issue!

Sorry for the complaints, and thanks for the great module!

**Comment by juliangruber** [comment]
no worries, this happens!
