### ISSUE TITLE
Outdated Deps?

### ISSUE THREAD

**Issue by heapwolf** [juliangruber/tape-run#75]
Are tape-run deps out of date?

```bash
> browserify --bare ./test | tape-run --node
```

```
.../projects/heapwolf/tonic/index.js:121
      for await (const value of v()) {
          ^^^^^

SyntaxError: Unexpected reserved word
```

**Comment by juliangruber** [comment]
This actually works:

```bash
echo "async function* f(){yield 'ok'};(async ()=>{for await (const o of f())console.log(o);})().then(()=>window.close());" | npx tape-run
ok
```

I'm assuming the `for await` isn't in the body of an async function itself?

**Comment by heapwolf** [comment]
That would be my first guess, but it was inside this async function (i removed the `for await of` in favor of a while loop so i could supoprt returns). I still get issues, ie `SyntaxError: Unexpected token *`, but all this code runs fine in the browser.

**Comment by heapwolf** [comment]
i deleted package-lock, that fixed it :-/
