### ISSUE TITLE
internal/streams/legacy.js:59 unhandled stream error on pipe

### ISSUE THREAD

**Issue by lorenzofox3** [juliangruber/tape-run#77]
I have a small test program:
```javascript
const test = require('tape');

test('foo', t=>{
    t.ok(true);
    t.end();
});
```

if I run ``browserify ./test/index.js | tape-run``

everything is fine.

However If I try to use a different browser, I keep having the same enigmatic error 
```Text
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Unexpected data: 
```
with any of the following command

```sh
 browserify ./test/index.js | tape-run --browser chrome

 browserify ./test/index.js | tape-run --browser=chrome

 browserify ./test/index.js | tape-run --browser="chrome"

 browserify ./test/index.js | tape-run --browser "chrome"
```

I am pretty sure the browsers are installed :) I am on MacOS 10.14.6

do you have any idea ? 

Thanks !

**Comment by fregante** [comment]
Same as https://github.com/juliangruber/browser-run/issues/145

It's already fixed but we're waiting for a release https://github.com/substack/browser-launcher/pull/45
