### ISSUE TITLE
Use a more recent browser-run version to pass the no-sandbox option to electron-stream

### ISSUE THREAD

**Issue by siosonel** [juliangruber/tape-run#82]
Related to https://github.com/juliangruber/electron-stream/pull/37, in order to use tape-run in a Docker container

**Comment by juliangruber** [comment]
Updated browser-run, next is tape-run https://github.com/juliangruber/browser-run/releases/tag/v10.1.0

**Comment by juliangruber** [comment]
https://github.com/juliangruber/tape-run/releases/tag/v9.0.0
