### ISSUE TITLE
Package name is too specific

### ISSUE THREAD

**Issue by 0x8890** [juliangruber/tape-run#9]
I use `tape-run` for running tests in a browser using my own test harness called `tapdance` which emits TAP, and it works flawlessly.

https://github.com/fortunejs/fortune/blob/master/package.json#L30
https://github.com/fortunejs/fortune/blob/master/test/browser.js

**Comment by juliangruber** [comment]
do you have a suggestion? `tap-run` wouldn't imply that it's for browsers, and i have `browser-run` already.

**Comment by 0x8890** [comment]
Maybe `tap-browser-run` since those are the keywords I searched for to find this module.
